# Generated by Django 5.0.2 on 2024-03-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartelera',
            options={'verbose_name': 'Cartelera', 'verbose_name_plural': 'Cartelera'},
        ),
        migrations.AlterModelOptions(
            name='cuerpoactivo',
            options={'ordering': ['legajo'], 'verbose_name': 'Cuerpo Activo', 'verbose_name_plural': 'Cuerpo Activo'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['cuartel', 'nombre', 'apellido'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='profesion',
            new_name='jerarquia',
        ),
    ]
