# Generated by Django 5.0.2 on 2024-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_cartelera_options_alter_cuerpoactivo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelera',
            name='novedad',
            field=models.CharField(default='Escriba aquí su novedad', max_length=200),
        ),
    ]
