# Generated by Django 5.0.2 on 2024-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_cartelera_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartelera',
            name='novedad',
            field=models.TextField(default='Escriba aquí su novedad'),
        ),
    ]
