# Generated by Django 5.0.2 on 2024-03-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_cartelera_novedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartelera',
            name='fechaPublicacion',
        ),
    ]
